config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, except: [:new, :index] do 
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new, :index]

  resource :session, only: [:new, :create, :destroy]
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  ord        :integer          not null
#  lyrics     :text
#  band_id    :integer          not null
#  album_id   :integer          not null
#  bonus      :boolean          default(FALSE)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Track < ApplicationRecord
    validates_presence_of :title, :ord, :band_id, :album_id
    validates :bonus, inclusion: { in: [true, false] }
    validates :ord, uniqueness: { scope: :album_id }

    belongs_to :album,
        class_name: :Album,
        foreign_key: :album_id,
        primary_key: :id

    belongs_to :band,
        class_name: :Band,
        foreign_key: :band_id,
        primary_key: :id
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    def new
        @album = Album.find(params[:album_id])
        @band = Band.find(@album.band_id)
        @tracks = Track.new
    end

    def create
        @track = Track.new(track_params)
        if @track.save
            redirect_to album_url(@track.album_id)
        else
            flash[:errors] = @track.errors.full_messages
            redirect_to album_url(@track.album_id)
        end
    end

    def show
        @track = Track.find(params[:id])
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
    def track_params
        params.require(:track).permit(:title, :ord, :lyrics, :band_id, :album_id, :bonus)
    end

end

app/views/tracks/new.html.erb
<h1>Create a new track</h1>

<form action="<%= tracks_url %>" method="POST">
<%= auth_token %>
Band: <select name="track[band_id]">
    <% Band.all.each do |band| %>
        <% if band.id == @band.id %>
            <option value="<%= band.id %>" selected><%= band.name %></option>
        <% else %>
            <option value="<%= band.id %>"><%= band.name %></option>
        <% end %>
    <% end %>
</select>
<br>
Album: <select name="track[album_id]">
    <% @band.albums.each do |album| %>
        <% if album.id == @album.id %>
            <option value="<%= album.id %>" selected><%= album.title %></option>
        <% else %>
            <option value="<%= album.id %>"><%= album.title %></option>
        <% end %>
    <% end %>
</select>

<br>
Title: <input type="text" name="track[title]" value="">
<br>
Track Number: <input type="text" name="track[ord]" value="">
<br>
Lyrics: <input type="text" name="track[lyrics]" value="">

<input type="radio" name="track[bonus]" value="false" checked> Original Track
<input type="radio" name="track[bonus]" value="true"> Bonus Track
<input type="submit" value="Enter track">
</form>

app/views/tracks/show.html.erb
<h1><%= @track.title %></h1>
<h2>By: <%= @track.band.name %></h2>
<h2>Album: <%= @track.album.title %></h2>

<a href="<%= album_url(@track.album.id) %>"><p>Back to album</p></a>